<div class="login-box">
      <div class="login-logo">
        <a href="/index"><b>Admin</b> Vengeance</a>
        <h1> <?= $x?></h1>
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Přihlášení do Administrace</p>
        <form action="login" method="post">
          <div class="form-group has-feedback">
            <input type="text" class="form-control" placeholder="Email" name="email">
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <input type="password" class="form-control" placeholder="Heslo" name="heslo">
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-4 pull-right">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Přihlásit se</button>
            </div><!-- /.col -->
          </div>
        </form>
        <div class="col-xs-12">
            <hr>
            <p>Všechna práva vyhrazena &copy; 2015 - 2016 <a href="http://pcsetup.cz">PC Setup</a></p>
        </div>
      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->