 <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Úprava produktu
            <small>Verze 1.0 - Ořezaná</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Hlavní Strana</a></li>
            <li class="active">Upload obrázků produktů</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">

          <!-- Main row -->
          <div class="row">
            <!-- Left col -->
            <div class="col-md-12">
              <!-- TABLE: LATEST ORDERS -->
              <div class="box box-info">
                <div class="box-body">
                   <div class="box-header with-border">
                              <h3 class="box-title">Nahrávání obrázků</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div><!-- /.box-header -->
<form action="/upload" method="post" enctype="multipart/form-data">

                <table border="0">
                   <tr>

                      <td>&nbsp;  </td><td> &nbsp;</td>

                  </tr>
                  <tr>

                      <td>   Obrázky:&nbsp;&nbsp;  </td><td> <input name="upload[]" type="file" multiple="multiple" /></td>

                  </tr>
                  <tr>
                     <td colspan="2"><br> <input type="submit" value="Nahrát"></td>
                  </tr>
                </table>




</form>
<h2 style="color:green"><?= $info ?></h2>
</div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
