           <div class="col-md-9 clearfix" id="checkout">
                        
                        <div class="box">
                            <form method="post" action="kosik/dokonceni">
                        
                           <ul class="nav nav-pills nav-justified">
                           <li><a href="kosik/platba"><i class="fa fa-money"></i><br>Volba Platby</a>
                                    </li>   
                                 <li><a href="kosik/doprava"><i class="fa fa-truck"></i><br>Způsob doručení</a>
                                    </li>                                                                  
                                    
                                    <li class="active"><a href="kosik/adresa"><i class="fa fa-map-marker"></i><br>Adresa</a>
                                    </li>
                                    <li class="disabled"><a><i class="fa fa-eye"></i><br>Rekapitulace objednávky</a>
                                    </li>
                                </ul>

                                <div class="content">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="firstname">Jméno*</label>
                                                <input type="text" class="form-control" id="firstname" name="firstname">
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="lastname">Příjmení*</label>
                                                <input type="text" class="form-control" id="lastname" name="lastname">
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.row -->

                                      <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="company">Firma</label>
                                                <input type="text" class="form-control" id="company" name="company">
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="street">Ulice a čp.*</label>
                                                <input type="text" class="form-control" id="street" name="street">
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.row -->

                                    <div class="row">
                                        <div class="col-sm-6 col-md-3">
                                            <div class="form-group">
                                                <label for="city">Město*</label>
                                                <input type="text" class="form-control" id="city" name="city">
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-3">
                                            <div class="form-group">
                                                <label for="zip">PSČ*</label>
                                                <input type="text" class="form-control" id="zip" name="zip">
                                            </div>
                                        </div>
                                   <!--     <div class="col-sm-6 col-md-3">
                                            <div class="form-group">
                                                <label for="state">State</label>
                                                <select class="form-control" id="state"></select>
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-3">
                                            <div class="form-group">
                                                <label for="country">Country</label>
                                                <select class="form-control" id="country"></select>
                                            </div>
                                        </div>
                                                     -->
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="phone">Telefon*</label>
                                                <input type="text" class="form-control" id="phone" name="phone">
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="email">Email*</label>
                                                <input type="text" class="form-control" id="email" name="email">
                                            </div>
                                        </div>

                                    </div>
                                    <!-- /.row -->
                                </div>

                                <div class="box-footer">
                                    <div class="pull-left">
                                        <a href="kosik/doprava" class="btn btn-default"><i class="fa fa-chevron-left"></i>Zpět na vobu dopravy</a>
                                    </div>
                                    <div class="pull-right">
                                        <button type="submit" class="btn btn-template-main">Pokračovat na dokončení objednávky<i class="fa fa-chevron-right"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <!-- /.box -->


                    </div>