   <div class="col-md-9 clearfix" id="checkout">

                        <div class="box">
                            <form method="post" action="kosik/adresa">
                                <ul class="nav nav-pills nav-justified">
                                 
                                    <li><a href="kosik/platba"><i class="fa fa-money"></i><br>Volba Platby</a>
                                    </li>                                
                                     <li class="active"><a href="kosik/doprava"><i class="fa fa-truck"></i><br>Způsob doručení</a>
                                    </li>
                                    <li class="disabled"><a><i class="fa fa-map-marker"></i><br>Adresa</a>
                                    </li>
                                    <li class="disabled"><a><i class="fa fa-eye"></i><br>Rekapitulace objednávky</a>
                                    </li>
                                </ul>

                                <div class="content">
                                    <div class="row">
                                  
                                           <div class="col-sm-6">
                                            <div class="box shipping-method">

                                                <h4>DPD</h4>

                                                <p>Zaslání balíkem.</p>

                                                <div class="box-footer text-center">

                                                    <input type="radio" name="delivery" value="2"> ZDARMA
                                                </div>
                                            </div>
                                        </div>
                                            
                                    </div>
                                    <!-- /.row -->

                                </div>
                                <!-- /.content -->

                                <div class="box-footer">
                                    <div class="pull-left">
                                        <a href="kosik/platba" class="btn btn-default"><i class="fa fa-chevron-left"></i>Zpět na vyběr způsobu platby</a>
                                    </div>
                                    <div class="pull-right">
                                        <button type="submit" class="btn btn-template-main">Pokračovat na vyplnění fakturačních údajů <i class="fa fa-chevron-right"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <!-- /.box -->

                                   
                    </div>
                    <!-- /.col-md-9 -->
