   <div class="col-md-9 clearfix" id="checkout">

                        <div class="box">
                            <form method="post" action="kosik/doprava">
                                <ul class="nav nav-pills nav-justified">
                                 
                                    <li class="active"><a href="kosik/platba"><i class="fa fa-money"></i><br>Volba Platby</a>
                                    </li>     
                                    <li class="disabled"><a><i class="fa fa-truck"></i><br>Způsob doručení</a>
                                    </li>                           
                                    
                                    <li class="disabled"><a><i class="fa fa-map-marker"></i><br>Adresa</a>
                                    </li>
                                    <li class="disabled"><a><i class="fa fa-eye"></i><br>Rekapitulace objednávky</a>
                                    </li>
                                </ul>

                                <div class="content">
                                    <div class="row">
                                                                                            
                                       

                                        <div class="col-sm-6">
                                            <div class="box payment-method">

                                                <h4>Převodem z účtu</h4>

                                                <p>Platba toho to typu trvá až 3 dny, dle banky.</p>

                                                <div class="box-footer text-center">

                                                    <input type="radio" name="payment" value="2"> ZDARMA
                                                </div>
                                            </div>
                                        </div>
                                
                                    <!-- /.row -->
                                    
                                           <div class="col-sm-6">
                                            <div class="box payment-method">

                                                <h4>Dobírka</h4>

                                                <p>Hotově či kartou, při převzetí zásilky.</p>

                                                <div class="box-footer text-center">

                                                    <input type="radio" name="payment" value="3">  50 Kč
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.row -->

                                </div>
                                <!-- /.content -->

                                <div class="box-footer">
                                    <div class="pull-left">
                                        <a href="kosik" class="btn btn-default"><i class="fa fa-chevron-left"></i>Zpět do košíku</a>
                                    </div>
                                    <div class="pull-right">
                                        <button type="submit" class="btn btn-template-main">Pokračovat na volbu doručení<i class="fa fa-chevron-right"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <!-- /.box -->

                                   
                    </div>
                    <!-- /.col-md-9 -->
