
<div class="col-sm-9">
<h1>Zboží</h1>
<p>Vyberte si prosím kategorii.
</p>
<ul class="nav nav-pills" id="rozcesti">
 <li class="3u"> <a href="/psi" class="text-center">
<img src="http://test.jelinkuvobchod.cz/images/PES.png" border="0" height="170px" class="enter-block"><br><br>
Pejsci
</a>
     </li>
	
<li class="3u"> <a href="/kocky" class="text-center">

<img src="http://test.jelinkuvobchod.cz/images/KOCKA.png" border="0" height="170px" class="center-block"><br>
 Kočičky
</a>   </li>
   </ul><br><br><br>
</div>
         
   
                    