<div class="col-sm-9">
<h1>Velkoobchodní odběr</h1>
    <p>Provozujete chovatelské potřeby, obchodujete s krmivy a zaujaly Vás naše výrobky? Nabízíme možnost individuálního odběru, kdy jsou podmínky následující: </p>
    <ul>
    <li>Odběr minimálně  50 kg smíšeného sortimentu</li>

<li>Osobní odběr, platba buď předem, převodem na účet, nebo v hotovosti na místě</li>

<li>Přeprava v rámci ČR – zajistíme a účtujeme v nejoptimálnějších cenách přepravních společností (kartony na tzv. jednorázové paletě) – platba celé dodávky předem, převodem na účet</li>


<li>V případě zájmu předložte živnostenské oprávnění/výpis z OR a zašleme Vám velkoobchodní ceník</li>

<li>Poradíme s nalezením nejoptimálnější cesty k našemu zboží!</li>

    
    </ul>
    <p>
Více informací získáte buď e-mailem na adresu <a href="mailto:info@chejn-krmiva.cz">info@chejn-krmiva.cz</a> nebo na telefonu 323 603 863!
   </p >
</div>